#!/glade/u/apps/opt/conda/envs/npl/bin/python
#PBS -N hello_pbs
#PBS -A UCOR0090
#PBS -j oe
#PBS -k eod
#PBS -q casper
#PBS -l walltime=00:05:00
#PBS -l select=1:ncpus=1:mpiprocs=1

import sys
print("Hello, world!!\n\n")

print("Python version:")
print(sys.version)
print("Version info:")
print(sys.version_info)
